spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unipfyy?&serverTimezone=UTC
    username: usuariojava
    password: senhajava
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
